#配置内部tomcat端口和路径
server:
  port: 1011
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: framework
  profiles:
    active: dev #默认环境(开发环境)
#  mvc:
#    static-path-pattern: /public/** #配置静态资源的映射路径：

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    url: jdbc:mysql://127.0.0.1:3306/db_test?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    max-active: 100
    max-idle: 20
    min-idle: 10
    initial-size: 5
    validationQuery: SELECT 1 FROM DUAL
    test-on-borrow: true
    test-on-return: true

  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true


  jackson:
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss
    mapper.default-view-inclusion: true
    time-zone: GMT+8

  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    static-path-pattern: /**
#mybatis:
#  #mybatis指定bean所在包
#  type-aliases-package: com.dandan.bean
#  #指定映射文件
#  mapper-locations: classpath:com/dandan/mapper/*.xml
#  #打印sql到控制台
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

alipay:
  app_id: 2021000118641572
  #应用私钥
  merchant_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCbwfYnyKJKllf7X7qPCkhV5jVHTwzAkqXWAcRRsjomxdsZqQ6LY1NHXvhrHuXLo8QxnBuhfbb2ni6r/JV0jrpn9lkXxeSBby9gW+QM96MuIFTBwfdFnlm6oyXYxfDH7neLhkcz2okW0efXVAy4xL36Kx7z7z6hU43WMScVPIxPJ+jTXs7BcAgYBIE/ftQ8AmnasAmmIdFIxK92XJPJ2YOBii6XkVYL0xwcHzjs6SijQCYscjRmGvO4gpVbHsEI7nCW0+csS6Y/NtJ1RBfDARRXjdFU9cv4YcjH8RzhXVs3j9jVUxSTU2RIHTjy+6aXjCRkdAB+KduPYOntr7GIc3nTAgMBAAECggEASjBo/yoho0VZQvKl+dv7+G5ekkik2lT/iJ/u0rsB19YGNoK/2sTEtgoWaW+eJREsMjUZNCKdM3rE4Ea/KXWSdFJyvVAVN1GuT0d1qHeL0jy0IlYxYYe7VZrAPDCML672Yg7je19sTOJOe9Ic/SU5GB/R7n7WZiFWPd/LreHZMxog5BWqTRjFAZb2gU6fVDbU7pMfw+YbtHSCFD2gdZ+C2sG47T0c7K+skvpnfYmc3RxP95zlPDUYK72FLgJOxhPWHVLZWsST95HtVpvuOHg3XaYAAdSPA4203WppWwQS0vBsCaYF9iau/0krGp1cdtVy0fCXZudy2rlG5RzrwMfPgQKBgQDSAeEmqeXAVuMzVfph6SX7jrhB43S7T16qViEY5vI2xdYzeJGzifso0iQckUTydxGEAqHilhoFS6xpTHabb88K+rbvbbi5a89uHT22YFlTIV0olFCHa8DrNx0HO3eyymu5brVJyqECqxcF6tGOi3dJFbBrNGzJvwezA1avIjUsnQKBgQC93o79fXgGMXulGifvWRvdIP6d+gAl5VInK4Tr94ElJ0L5jhaDl2QDA1SDbXpE0EGu/X0nv8eN+bbveQK2IMb9SNl39faooC6JJSs2T5OMi+UZRUQpc9sOSVKFItWq3KWj2FzYEWrTuKTAtnq7ozmmGuf7970e6uK23O6342SdLwKBgF+sjYeQxWPf8bg0hlJO5of5WEZkOo0PNsCBZqiypkx/yvs+BZr21J6fReZh5DhWOHucu2XAHnClLhH2zN45jOiime7wXMTUsfanibLpqCgwPgG7uAhJ9eTzAd2GoRyqDXO4VQ0eLEZL7bw7Y2b+cMSyBeKBSsKKrhZHAhndir4dAoGAI4Hbe8xbBc17MgUSMtCXRWNGOoTmQjAAjRK2aOqAXFJbVBAeZb2KFoYo5+sxUm0f23nMTgKvbv2kGGSo/SZkEDnvcV+uIRrTmRI6Yo2/Kil/TpqFhLsF3EYaCIvbKXjaASoVMtMPB0kghmmZyj1cKpQdjiFmXMHQZCItAnaj+kECgYAGz9K64w+zfu6P+Pz9RYJUu3KL6hkpUqvfbLQgFAu6I9j6OHSa7/aaeTYoBwOswE2zH5GURd++AsE3ZtqryC8yUJK5hiEKr5JTUa5pe//R9MQf7Lv1ivj1Er3qpqw4jfUKq8GxHUhOskUEMalNhvjfSjyKgCva/3dUA6GPYxaodg==
  #支付宝公钥
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqDSGa3uES4PY7MkEcnS2pjBKXZYuJiTR9WRCYoYFffJTVB2Cygll1wVkfYnZS5D1+3gc+i+FshoSkd/0R14GEhdKnGVRG/z4a8AEwcFLjmia0ZBPj7x2JBU4inID3gRh4ggDJhFg1XXAn4fw5xBa2TyNg/ZodnJ5khQl5BmAUMHghxK5lAeGNam4OYv9e1vGCcesdrPE54ciGOsCrGbKI+pdj7W00pSKEvo6V8kIW1wYQRq82sg/YrQ0qGax2rLhM7OHbPUXq7/HqfecGsbPr4zwWPZNXKelCWOAFNOXHViUzkUAEf3oXLfdV6Wa1OBT7iHTu2fFcUgqXBXlh1KPKwIDAQAB
  notify_url: http://e5f8b15.cpolar.io/alipay/returnNotifyUrl
  return_url: http://e5f8b15.cpolar.io/alipay/returnUrl
  sign_type: "RSA2"
  charset: "utf-8"
  gatewayUrl: "https://openapi.alipaydev.com/gateway.do"

logging:
  level:
    root: 'info'
  pattern:
    console: '%d{yyyy:MM:dd HH:mm:ss.SSS} - [%thread] - [%-5level] - %c[%L] :【 %msg】%n '
